cliqz-oss/browser-f

magic_build_and_package.sh

update extension version

---

cliqz.cfg
mozilla-release/browser/components/preferences/in-content/search.js
mozilla-release/browser/components/preferences/search.js

@chrmod fixes https://github.com/cliqz-oss/browser-f/issues/45

Branding: add CLIQZ Tour button in the Help menu #45

---

mozilla-release/widget/cocoa/nsChildView.mm

See https://bugzilla.mozilla.org/show_bug.cgi?id=1187613

BROWSER-99: Backport bugfix 1187613

---

magic_build_and_package.sh

@maxim-cliqz please verify if that solves our problem

Build: clean old *.pyc

---

mozilla-release/browser/base/content/aboutDialog.css
mozilla-release/browser/base/content/aboutDialog.js
mozilla-release/browser/base/content/aboutDialog.xul

BROWSER-66: remove FF version from "About CLIQZ" dialog

---

mozilla-release/build/gen_build_properties.py
mozilla-release/build/upload.py

Affected by https://bugzilla.mozilla.org/show_bug.cgi?id=1198179

Build: updating CLIQZ upload scripts

---

cliqz.cfg
l10n/de/browser/chrome/browser/preferences/main.dtd
mozilla-release/browser/app/profile/firefox.js
mozilla-release/browser/base/content/browser-tabview.js
mozilla-release/browser/components/moz.build
mozilla-release/browser/components/nsBrowserContentHandler.js
mozilla-release/browser/components/nsBrowserGlue.js
mozilla-release/browser/components/preferences/in-content/main.js
mozilla-release/browser/components/preferences/in-content/main.xul
mozilla-release/browser/components/sessionstore/content/aboutSessionRestore.js
mozilla-release/browser/components/sessionstore/nsSessionStartup.js
mozilla-release/browser/components/tabview/test/browser_tabview_bug656778.js
mozilla-release/browser/locales/en-US/chrome/browser/preferences/main.dtd
mozilla-release/browser/themes/shared/incontentprefs/preferences.inc.css

Startup preferences

---

cliqz.cfg
mozilla-release/browser/branding/cliqz/pref/firefox-branding.js
repack/distribution/distribution.ini

@chrmod 
https://github.com/cliqz-oss/browser-f/issues/128

show cliqz onboarding as first/only tab

---

mozilla-release/browser/app/profile/firefox.js

reverting the change from @alver-cliqz 
cc @chrmod

enforce extension signature

---

magic_build_and_package.sh

bumb extension version

---

magic_upload_files.sh

For following new build system

DB-98: fix in upload script

---

mozilla-release/config/rules.mk

@alver-cliqz 
can we please start a release build after merging this PR?

bump extension version

---

mozilla-release/browser/locales/generic/profile/bookmarks.html.in

Implements: https://cliqztix.atlassian.net/browse/DB-321
(don't ask me why some tags are not closed..)

Branding: removing 'Getting Starter' mozilla bookmark DB-321

---

cliqz_env.sh
magic_build_and_package.sh
magic_upload_files.sh
sign_mac.sh

Implements: https://cliqztix.atlassian.net/browse/DB-432

DB-432 Build: fix mar signing on Windows / Linux

---

mozilla-release/browser/components/privatebrowsing/content/aboutPrivateBrowsing.css

DB-448: hide anti tracking box on private windows

---

l10n/de/browser/chrome/browser/browser.properties
mozilla-release/browser/components/nsBrowserGlue.js
mozilla-release/browser/locales/en-US/chrome/browser/browser.properties

DB-425: Change One time notification for disable add-ons notification

---

cliqz.cfg
mozilla-release/config/rules.mk

extension update + re-verify signatures at upgrade and downgrade 

---

mozilla-release/browser/base/content/aboutDialog.xul

Implements: https://cliqztix.atlassian.net/browse/DB-435

DB-435 replacing cliqz support link

---

l10n/de/browser/profile/bookmarks.inc
mozilla-release/browser/locales/en-US/profile/bookmarks.inc
mozilla-release/browser/locales/generic/profile/bookmarks.html.in

Implements: https://cliqztix.atlassian.net/browse/DB-321

Branding: default bookmarks changed

---

mozilla-release/toolkit/mozapps/extensions/internal/XPIProvider.jsm

DB-481: require signature for all types of add-ons

---

mozilla-release/config/rules.mk

@chrmod @alver-cliqz @maxim-cliqz

DB-501: Integrate extension 1.3.0

---

mozilla-release/config/rules.mk

@chrmod squash-merge please :)

Merge back release to master

---

cliqz_env.sh
magic_build_and_package.sh
mozilla-release/build/upload.py
mozilla-release/toolkit/mozapps/installer/linux/rpm/mozilla.spec
mozilla-release/toolkit/mozapps/installer/package-name.mk
mozilla-release/toolkit/mozapps/installer/packager.py
mozilla-release/toolkit/mozapps/installer/upload-files.mk

@alver-cliqz @maxim-cliqz please take a look
note that:
the way MOZ_UPDATE_CHANNEL is used have changed

DB-515: enable packaged linux builds: rpm + deb

---

l10n/de/browser/chrome/overrides/netError.dtd
mozilla-release/browser/locales/en-US/chrome/overrides/netError.dtd
mozilla-release/netwerk/base/security-prefs.js

SSL Error Reporting service + update messaging

---

mozilla-release/config/rules.mk

DB-502: Integrate extension 1.4.0

---

mozilla-release/browser/components/shell/nsWindowsShellService.cpp

Remove Firefox nodes, if CLIQZ accidently rewrite it

DB-604: Fix intersection in Windows registry between CLIQZ and Firefox

---

mozilla-release/browser/components/nsBrowserGlue.js

DB-606: Reverted changes for DB-471

---

mozilla-release/browser/components/shell/nsWindowsShellService.cpp
mozilla-release/browser/installer/windows/nsis/installer.nsi
mozilla-release/browser/installer/windows/nsis/shared.nsh

Move patching functional to installer (for install and update phase)

DB-618: patch for fixing Firefox and Cliqz intersection

---

mozilla-release/config/rules.mk

DB-647: integrate extension 1.5.*

---

Dockerfile
Jenkinsfile
magic_upload_files.sh
sign_lin.sh

Also, we do submit build do APT repository!

DB-588: Linux build driven via Jenkinsfile and Docker #298 

---

Jenkinsfile

scm command updated to support fetching specific commits

Build: should fail without CQZ_COMMIT

---

mozilla-release/browser/installer/removed-files.in
mozilla-release/browser/installer/windows/nsis/shared.nsh

Because it moved to System Addon
Let's check PR before merge

DB-659: remove distribution/extensions/cliqz@cliqz.com.xpi

---

mozilla-release/browser/base/content/PrivateTabUI.jsm
mozilla-release/browser/base/content/browser.css
mozilla-release/browser/base/content/browser.js
mozilla-release/browser/base/content/tabbrowser.xml
mozilla-release/browser/base/jar.mn

Paint urlbar background grey, when a private tab is active.

DB-652: Private tab indication

---

l10n/de/browser/chrome/browser/browser.dtd
l10n/de/browser/chrome/browser/preferences/security.dtd
l10n/de/browser/chrome/browser/tabbrowser.properties
mozilla-release/browser/base/content/browser.js
mozilla-release/browser/components/controlcenter/content/panel.inc.xul
mozilla-release/browser/components/preferences/in-content/security.js
mozilla-release/browser/components/preferences/in-content/security.xul
mozilla-release/browser/locales/en-US/chrome/browser/browser.dtd
mozilla-release/browser/locales/en-US/chrome/browser/preferences/security.dtd
mozilla-release/browser/locales/en-US/chrome/browser/tabbrowser.properties
mozilla-release/browser/themes/shared/controlcenter/https-everywhere-disabled.svg
mozilla-release/browser/themes/shared/controlcenter/https-everywhere-enabled.svg
mozilla-release/browser/themes/shared/controlcenter/panel.inc.css
mozilla-release/browser/themes/shared/jar.inc.mn

@maxim-cliqz @chrmod  feedback welcomed !

Cp 1930 - HttpsEverywhere in identity popup & about:preferences#security

---

mozilla-release/config/rules.mk

DB-574: Enable HTTPS Everywhere in release builds

---

l10n/de/browser/chrome/browser/preferences/security.dtd
mozilla-release/browser/components/preferences/handlers.css
mozilla-release/browser/components/preferences/in-content/security.js
mozilla-release/browser/components/preferences/in-content/security.xul
mozilla-release/browser/locales/en-US/chrome/browser/preferences/security.dtd
mozilla-release/toolkit/mozapps/extensions/content/extensions.xml

DB-565: Last Pass integration

---

cliqz_env.sh
mozilla-release/browser/config/cliqz.mozconfig

For fix build without MOZ_SOURCE_CHANGESET (we use git, not hg like FF do)

DB-700: remove MOZ_SOURCE_REPO

---

l10n/de/browser/chrome/browser/preferences/security.dtd
mozilla-release/browser/components/preferences/in-content/security.xul
mozilla-release/browser/locales/en-US/chrome/browser/preferences/security.dtd
mozilla-release/config/rules.mk

Small text changes + styling for HTTPS Everywhere and Last Pass integration

---

mozilla-release/config/rules.mk

update https everywhere

---

mozilla-release/config/rules.mk

DB-783: extension 1.7.2

---

l10n/de/browser/chrome/browser/aboutAccounts.dtd
l10n/de/browser/chrome/browser/aboutCertError.dtd
l10n/de/browser/chrome/browser/aboutDialog.dtd
l10n/de/browser/chrome/browser/aboutPrivateBrowsing.dtd
l10n/de/browser/chrome/browser/aboutPrivateBrowsing.properties
l10n/de/browser/chrome/browser/aboutSessionRestore.dtd
l10n/de/browser/chrome/browser/aboutTabCrashed.dtd
l10n/de/browser/chrome/browser/browser.dtd
l10n/de/browser/chrome/browser/browser.properties
l10n/de/browser/chrome/browser/preferences/advanced.dtd
l10n/de/browser/chrome/browser/preferences/preferences.properties
l10n/de/browser/crashreporter/crashreporter-override.ini
l10n/de/browser/installer/custom.properties
l10n/de/browser/pdfviewer/viewer.properties
l10n/de/browser/profile/bookmarks.inc
l10n/de/security/manager/chrome/pipnss/pipnss.properties
l10n/de/security/manager/chrome/pippki/certManager.dtd
l10n/de/suite/chrome/common/pref/pref-certs.dtd
l10n/de/toolkit/crashreporter/crashreporter.ini

@luciancor, please review. (sorry, Dominik S is not part of this repository it seems)

Sie --> du changes

---

l10n/de/toolkit/chrome/mozapps/extensions/blocklist.dtd
mozilla-release/toolkit/locales/en-US/chrome/mozapps/extensions/blocklist.dtd

text changes in add-ons security warning message

---

mozilla-release/config/rules.mk

DB-823: update extension to 1.8.0

---

mozilla-release/config/rules.mk

DB-821: update httpsEverywhere to 5.2.1

---

mozilla-release/browser/components/AutoPrivateTab.js

This fixes `Error: chromeWindow.gBrowser is null in AutoPrivateTab.js` when opening new browser windows and generally filters out more requests from heavy processing.

DB-810: Ignore non-http navigations better

---

mozilla-release/toolkit/mozapps/extensions/internal/XPIProviderUtils.js

DB-822: Fix telemetry sent for extension blocking

---

mozilla-release/toolkit/mozapps/extensions/content/extensions.xul

Was erroneously removed during merge.

DB-830: Put back hidden block wrapping extensions search bar

---

mozilla-release/config/rules.mk

DB-833: Update extension to 1.8.1

---

mozilla-release/browser/confvars.sh

DB-847 - Fix Safe browsing

---

mozilla-release/browser/components/customizableui/CustomizableUI.jsm

DB-868: Control Center - keep close to urlbar after restore defaults

---

mozilla-release/config/rules.mk

@alver-cliqz updated HTTPS Everywhere https://github.com/cliqz-oss/https-everywhere/releases/tag/CLIQZ_5.2.4

DB-871: update HTTPS Everywhere

---

mozilla-release/config/rules.mk

DB-869: update extension version to 1.9.0

---

Jenkinsfile
build-helpers.groovy
linux.Jenkinsfile
mac.Jenkinsfile
mac.Vagrantfile
win.Jenkinsfile
win.Vagrantfile

new build parameters will to control:
* VM rebuild (destroy before run) in case of box changes
* VM CPU and memory
* VM VNC port

Build: params for virtualization

---

mozilla-release/config/rules.mk

DB-869: update extension version to 1.9.1

---

mozilla-release/browser/extensions/moz.build

we don't know the reason why it is there so better to not have it

DB-855: removing WebCompat extension

---

mozilla-release/browser/base/content/browser.js
mozilla-release/browser/base/content/browser.xul

Please let me know if there is any conflict when merging this and DB-919

DB-918: Duplicated Tab should be opened next to current one

---

mozilla-release/browser/components/migration/FirefoxProfileMigrator.js

DB-985: Fix and complete implementation of Firefox Data import into Cliqz browser

---

LICENSE

Add line breaks to the file to make this file more user friendly
and readable.

Fix for the LICENSE file

---

Jenkinsfile

Change build script to publish to Balrog only if all build complete
Email notification (for browser only, without extension information yet)

DB-525: email notifications

---

l10n/de/browser/chrome/browser/preferences/privacy.dtd

German language fix Sie to du on privacy preferences page

---

Jenkinsfile.release

More accurate detection of CQZ_BUILD_DE_LOCALIZATION value for Windows build

Fix build script

---

l10n/de/toolkit/chrome/global/about.dtd

deleted wrong word in German version of about:

---

l10n/de/browser/chrome/overrides/netError.dtd
mozilla-release/browser/locales/en-US/chrome/overrides/netError.dtd

fix text on netError.dtd

---

mozilla-release/browser/components/shell/ShellService.jsm
mozilla-release/browser/installer/windows/nsis/installer.nsi
mozilla-release/browser/installer/windows/nsis/shared.nsh
mozilla-release/browser/installer/windows/nsis/uninstaller.nsi
mozilla-release/toolkit/mozapps/installer/windows/nsis/common.nsh

Need to recheck:
1. Update to higher version
2. Installation on Windows 8
3. Make as default on silent installation

DB-1041: some fixes for Windows installer

---

mozilla-release/browser/base/content/tabbrowser.xml
mozilla-release/docshell/base/nsDocShell.cpp
mozilla-release/dom/base/nsFrameLoader.cpp
mozilla-release/toolkit/content/widgets/browser.xml

@alver-cliqz @maxim-cliqz cherry pick this fix to release

DB-911: Quick fixing of cross-window private tabs transplantation

---

l10n/de/browser/chrome/browser/preferences/donottrack.dtd

Ihre -> deine Aktivitäten text change DE only

---

mozilla-release/browser/base/content/PrivateTabUI.jsm
mozilla-release/browser/base/content/tabbrowser.xml
mozilla-release/docshell/base/nsDocShell.cpp
mozilla-release/docshell/base/nsIWebNavigation.idl
mozilla-release/dom/base/nsFrameLoader.cpp
mozilla-release/dom/ipc/TabChild.cpp
mozilla-release/dom/ipc/TabParent.cpp
mozilla-release/toolkit/content/widgets/browser.xml
mozilla-release/toolkit/modules/PrivateBrowsingUtils.jsm

Partially reverts #481 and adds better fix instead.

DB-1106: Fix moving private tabs between windows

---

mozilla-release/browser/base/content/browser.js

DB-1139: hide about:cliqz

---

mozilla-release/config/rules.mk

DB-1144: update extension version

---

mozilla-release/config/rules.mk

@alver-cliqz we need this one for 1.10.0

Increase extension version

---

Jenkinsfile
build-helpers.groovy
sign_mac.sh

Pull request automated builder.

Pr build final

---

Jenkinsfile
build-helpers.groovy

Restored withVagrant function to previous version, without handling a case where node is already created and should be reused.

Release fix PR

---

Jenkinsfile
build-helpers.groovy

Because now we have several osx builder slaves i implemented lb between them as well as hardcoded docker slaves to always use machines in US region

Osx pr lb and Windows region for docker slave

---

Jenkinsfile.release

Send email if problem with balrog happened.

DB-1228: fix in release build scripts.

---

l10n/de/toolkit/chrome/global/aboutSupport.dtd
mozilla-release/toolkit/locales/en-US/chrome/global/aboutSupport.dtd

DB-1171: Changed intro on about:support. Added Cliqz support link in DE and EN

---

l10n/de/toolkit/chrome/global/resetProfile.dtd

DB-1171: text changes for DE refresh

---

Jenkinsfile.lin
Jenkinsfile.mac
Jenkinsfile.win

Implmented keys the way mozilla wants them

---

mozilla-release/browser/components/AutoForgetTabsMonitor.jsm
mozilla-release/build/pgo/server-locations.txt
mozilla-release/docshell/test/chrome/chrome.ini
mozilla-release/docshell/test/chrome/test_docRedirect.sjs
mozilla-release/docshell/test/chrome/test_docRedirect.xul
mozilla-release/uriloader/base/nsDocLoader.cpp
mozilla-release/uriloader/base/nsIWebProgressListener.idl

I suggest to wait with merging till Mozilla finally accepts our patch.

DB-1255: Mozilla's requests plus a test

---

mozilla-release/browser/components/customizableui/CustomizableUI.jsm

Remove obsolete buttons from default navBar placements

---

cliqz_env.sh
magic_build_and_package.sh
mozilla-release/build/upload.py

DB-1280: prepare an archive with build symbols and upload to S3

---

mozilla-release/toolkit/mozapps/extensions/internal/XPIProvider.jsm

SystemAddons: do not uninstall them every time an update comes

---

mozilla-release/toolkit/mozapps/extensions/internal/XPIProvider.jsm

Reverts cliqz-oss/browser-f#596
@alver-cliqz

Revert "SystemAddons: do not uninstall them every time an update comes"

---

mozilla-release/toolkit/mozapps/installer/linux/rpm/mozilla.spec

Background: http://backreference.org/2011/09/17/some-tips-on-rpm-conditional-macros/
@alver-cliqz , @chrmod

DB-1299: Fix for Linux builds

---

mozilla-release/browser/branding/cliqz/branding.nsi
mozilla-release/browser/installer/windows/nsis/stub.nsi

DB-1306: changes in mini installer for Windows.

---

mozilla-release/browser/locales/search/list.json
mozilla-release/browser/locales/searchplugins/startpage-de.xml

EX-4531: "StartPage" Supplementary Search Engine DE version

---

mozilla-release/browser/components/preferences/handlers.css
mozilla-release/browser/components/preferences/in-content/security.js

Reverts cliqz-oss/browser-f#617
@mai-cliqz

Revert "DB-1325: Integrate 1Password"

---

mozilla-release/browser/components/preferences/in-content/preferences.js

DB-1354: Connect (DMO Pairing): Remove AB test in Browser

---

mozilla-release/toolkit/components/url-classifier/SafeBrowsing.jsm

DB-1310: Get URL for "Report deceptive website function"

---

mozilla-release/browser/components/AutoForgetTabsService.js
mozilla-release/toolkit/modules/BloomFilterUtils.jsm

If it doesn't exist - use from installation folder. With this solution we can update list with updating extension only, no needs to update whole browser.

DB-1284: using adult-domains from extension

---

mozilla-release/browser/components/preferences/in-content/security.js

@alver-cliqz 
We simplify the way how we communicate with HttpsEverywhere 
Needs: https://github.com/cliqz-oss/https-everywhere/commit/f82fb0d9f5721318a4a53be11bf7ea137d4cb4ed

DB-1450: toggle HTTPS Everywhere by simply changing the pref

---

Jenkinsfile.release

This reverts commit a88ada40f45bf78b52cbb9a2e479605355f02ec9.

Revert "Temporary disable linux build, problem with rustup-init script"

---

Jenkinsfile.mac

Added xz installation to bootstrap step for Mac Os

Added xz installation as part of Mac OS bootstrap stage

---

mozilla-release/browser/themes/linux/cliqz/theme.css
mozilla-release/browser/themes/osx/cliqz/theme.css
mozilla-release/browser/themes/windows/cliqz/theme.css

@alver-cliqz @luciancor @chrmod

DB-1490: x icon for active tab in blue theme

---

mozilla-release/widget/cocoa/nsCocoaWindow.mm

Based on https://hg.mozilla.org/releases/mozilla-beta/rev/ba626b811d73

DB-1493: fix for system buttons for Mac OS High Sierra (10.13)

---

l10n/de/browser/chrome/browser/preferences/preferences.dtd
l10n/de/browser/chrome/browser/preferences/privacy.dtd
l10n/de/browser/chrome/browser/preferences/search.dtd
l10n/de/browser/chrome/browser/preferences/security.dtd
mozilla-release/browser/components/preferences/in-content-new/connect.js
mozilla-release/browser/components/preferences/in-content-new/connect.xul
mozilla-release/browser/components/preferences/in-content-new/jar.mn
mozilla-release/browser/components/preferences/in-content-new/main.js
mozilla-release/browser/components/preferences/in-content-new/main.xul
mozilla-release/browser/components/preferences/in-content-new/moz.build
mozilla-release/browser/components/preferences/in-content-new/preferences.js
mozilla-release/browser/components/preferences/in-content-new/preferences.xul
mozilla-release/browser/components/preferences/in-content-new/privacy.js
mozilla-release/browser/components/preferences/in-content-new/privacy.xul
mozilla-release/browser/components/preferences/in-content-new/search.xul
mozilla-release/browser/locales/en-US/chrome/browser/preferences/preferences.dtd
mozilla-release/browser/locales/en-US/chrome/browser/preferences/privacy.dtd
mozilla-release/browser/locales/en-US/chrome/browser/preferences/search.dtd
mozilla-release/browser/locales/en-US/chrome/browser/preferences/security.dtd

Most of changes moved from old Preferences view to new one.

DB-1487: return back all changes related to Preferences page

---

mozilla-release/browser/themes/linux/cliqz/theme.css
mozilla-release/browser/themes/osx/cliqz/theme.css
mozilla-release/browser/themes/windows/cliqz/theme.css

@chrmod Fixed new tab icon on Linux as well

UI improvements on CliqzTab and CliqzBrowser

---

mozilla-release/browser/base/content/aboutDialog-appUpdater.js

Together with usual browser update checking

DB-1428: trigger System Addon extensions update check

---

mozilla-release/browser/components/preferences/in-content-new/privacy.js
mozilla-release/browser/components/preferences/in-content-new/privacy.xul

Additional content on wrong pages and https_everywhere option

DB-1497: fix preferences

---

mozilla-release/browser/components/about/AboutRedirector.cpp

DB-1523: use the chrome url for freshtab

---

mozilla-release/browser/components/preferences/in-content/privacy.js

DB-1561: Handle HTTPS Everywhere as a WebExtension

---

mozilla-release/browser/base/content/browser-pageActions.js
mozilla-release/browser/base/jar.mn
mozilla-release/browser/modules/PageActions.jsm
mozilla-release/browser/modules/moz.build

(ifdefened the code, related to Mozilla Sync service)

DB-1556: fix page actions

---

mozilla-release/browser/components/nsBrowserContentHandler.js
mozilla-release/browser/components/sessionstore/SessionStore.jsm

DB-1559: fix addFreshTab feature

---

mozilla-release/browser/themes/linux/cliqz/theme.css
mozilla-release/browser/themes/osx/cliqz/theme.css
mozilla-release/browser/themes/windows/cliqz/theme.css

EX-6109:[Blue theme] fix close button hover issue on Windows touch theme

---

mozilla-release/toolkit/mozapps/extensions/internal/XPIProvider.jsm

DB-1595: system addons can be userDisabled in Cliqz

---

cliqz_env.sh
mozilla-release/build/gen_build_properties.py
mozilla-release/config/rules.mk

DB-1335: update build script - use CQZ_RELEASE_CHANNEL evnvar

---

mozilla-release/toolkit/modules/PrivateBrowsingUtils.jsm

This reverts commit c547eccd7302bf939562baf3cad016fb5123f516.

Revert "DB-1635: fix aBrowser.loadContext undefined."

---

mozilla-release/browser/components/newtab/aboutNewTabService.js

This reverts commit aaa32779354f1c349127cf90af075076100423c6.

DB-1681: Revert "hide page action in forget window (#855)"

---

l10n/de/browser/chrome/browser/browser.dtd
l10n/de/browser/chrome/browser/preferences/search.dtd
mozilla-release/browser/locales/en-US/chrome/browser/browser.dtd
mozilla-release/browser/locales/en-US/chrome/browser/preferences/search.dtd
mozilla-release/toolkit/locales/en-US/chrome/mozapps/profile/profileSelection.properties
sign_win.bat

1. Remove duplicate entries from DTD
2. Fix "localization repack" errors
3. Use proper 7z path for sign process on Windows

DB-1731: fixes after merge

---

mozilla-release/browser/branding/cliqz/branding.nsi
mozilla-release/browser/installer/windows/nsis/installer.nsi

DB-1736: change text on shortcuts from "Cliqz" to "Cliqz Internet"

---

mozilla-release/browser/installer/windows/nsis/shared.nsh

DB-1743: rename "Cliqz" to "Cliqz Internet" with updating process

---

mozilla-release/browser/base/content/browser.js
mozilla-release/browser/base/content/global-scripts.inc
mozilla-release/browser/modules/PageActions.jsm

Also remove developer helper file (browser-development-helpers.js) from all our builds

DB-1713: remove "Add Search Engine" function from Page Action list

---

cliqz.cfg

@luciancor We always remove this file since we don't want users who switch to another profile have the problem again.
cc @alver-cliqz

Remove userChrome.css from user profile

---

mozilla-release/toolkit/components/telemetry/TelemetryEnvironment.jsm

Record the value of the lightweightThemes.selectedThemeID preference.

Record the theme pref

---

Dockerfile

Removed unneeded apt-get update that would fail on keyserver

apt-get update failing on a keyserver

---

l10n/de/browser/chrome/browser/migration/migration.dtd
l10n/de/browser/chrome/browser/migration/migration.properties
mozilla-release/browser/components/migration/BrowserProfileMigrators.manifest
mozilla-release/browser/components/migration/FirefoxProfileMigrator.js
mozilla-release/browser/components/migration/MigrationUtils.jsm
mozilla-release/browser/components/migration/content/migration.xul
mozilla-release/browser/locales/en-US/chrome/browser/migration/migration.dtd
mozilla-release/browser/locales/en-US/chrome/browser/migration/migration.properties

GB-10 | Add a possibility to import data from the other browsers

---

l10n/de/browser/browser/preferences/cliqz.home.ftl
mozilla-release/browser/components/preferences/in-content/cliqz.home.js
mozilla-release/browser/components/preferences/in-content/cliqz.home.xul
mozilla-release/browser/components/preferences/in-content/jar.mn
mozilla-release/browser/components/preferences/in-content/main.js
mozilla-release/browser/components/preferences/in-content/main.xul
mozilla-release/browser/components/preferences/in-content/preferences.js
mozilla-release/browser/components/preferences/in-content/preferences.xul
mozilla-release/browser/locales/en-US/browser/preferences/cliqz.home.ftl
mozilla-release/browser/themes/shared/incontentprefs/cliqz.home.inc.css
mozilla-release/browser/themes/shared/incontentprefs/preferences.inc.css

@alver-cliqz @chrmod @private-face

DB-1766: added changes for about preferences

---

mozilla-release/netwerk/dns/nsDNSService2.cpp
mozilla-release/netwerk/dns/nsDNSService2.h

- Patch from https://gitweb.torproject.org/tor-browser.git/commit/?h=tor-browser-60.1.0esr-8.0-1&id=e7f6531f9072f1632f71815e57aa79b76406f853

[Tor] Prevent DNS leaks with SOCKS proxy

---

mozilla-release/config/rules.mk

This probably got lost when I split the Tor changes in several PRs.

Fix onionmode xpi download in build

---

l10n/de/browser/chrome/browser/preferences/cliqzpref.dtd
mozilla-release/browser/locales/en-US/chrome/browser/preferences/cliqzpref.dtd
mozilla-release/browser/themes/shared/incontentprefs/preferences.inc.css

Change [auto]-forget tab copy on about:preferences#privacy

---

l10n/de/browser/chrome/browser/preferences/cliqzpref.dtd
mozilla-release/browser/components/preferences/in-content/cliqz.home.xul
mozilla-release/browser/locales/en-US/chrome/browser/preferences/cliqzpref.dtd
mozilla-release/browser/locales/en-US/chrome/browser/preferences/main.dtd

I have added some visual improvements for Preferences/Home page.
@alver-cliqz @luciancor @chrmod @private-face

DB-1766-update: added minor updates to preferences home

---

mozilla-release/browser/branding/cliqz/pref/firefox-branding.js

TODO: cliqz.cfg must be removed

DB-1845, DB-1841: fix update URL and about dialog

---

l10n/de/browser/chrome/browser/preferences/cliqzpref.dtd
mozilla-release/browser/components/preferences/in-content/privacy.xul
mozilla-release/browser/locales/en-US/chrome/browser/preferences/cliqzpref.dtd

@alver-cliqz @chrmod @private-face @tsl143

DB-1852: updated texts for Consentrick

---

mozilla-release/devtools/server/actors/targets/browsing-context.js

@alver-cliqz @chrmod @private-face @tsl143

DB-1821: fixed console error when click on Import now

---

mozilla-release/browser/app/profile/firefox.js

DB-1847: turn off e10s for webextension for now

---

mozilla-release/browser/app/profile/firefox.js
mozilla-release/toolkit/modules/addons/WebRequestContent.js

Revert 9c8f59ffdf1a699e61898b3c52a65dc55a6e7ffa
Revert 2e2d56871393ab538b00560eaf9b17bce366e381

DB-1847: revert commits to make webextensions works as it must in FF 62

---

l10n/de/browser/browser/preferences/cliqz.home.ftl
mozilla-release/browser/components/preferences/in-content/cliqz.home.xul
mozilla-release/browser/locales/en-US/browser/preferences/cliqz.home.ftl

@alver-cliqz @luciancor @chrmod @tsl143

DB-1860: fixed translations for Homepage section

---

mozilla-release/browser/components/preferences/in-content/privacy.js

@alver-cliqz @chrmod @luciancor @tsl143

DB-1861: fixed re-consent disable/enable switcher

---

mozilla-release/browser/components/nsBrowserContentHandler.js

DB-1864: fixed user pre-defined pages for homepage | new window

---

mozilla-release/browser/components/preferences/in-content/search.js

@alver-cliqz @luciancor @chrmod

DB-1820: restoring engine shortcut / alias

---

mozilla-release/toolkit/components/normandy/content/AboutPages.jsm
mozilla-release/toolkit/components/normandy/content/shield-content-process.js

@alver-cliqz @luciancor @tsl143

DB-1872: removed about studies chapter from about

---

mozilla-release/browser/base/content/browser.css

This ensures the removal of Browser action without impacting any functionality of the https-everywhere.

Allow installation of AMO version of https-everywhere in DB

---

mozilla-release/browser/components/nsBrowserContentHandler.js

@alver-cliqz @tsl143 @private-face @konark-cliqz

DB-1878: start up page option fixed

---

mozilla-release/browser/components/sessionstore/SessionStore.jsm

@alver-cliqz @luciancor @private-face @tsl143

DB-1894: fixed Cliqz Update Process + SessionRestore uncaught exception

---

mozilla-release/browser/components/nsBrowserContentHandler.js

@alver-cliqz @private-face @tsl143

DB-1849: blank tab is loaded only at startup without home page checked

---

mozilla-release/browser/base/content/browser.js
mozilla-release/browser/components/newtab/aboutNewTabService.js
mozilla-release/browser/components/newtab/jar.mn
mozilla-release/browser/components/newtab/moz.build
mozilla-release/browser/modules/moz.build

Also we need to check with each Firefox's update what else we need to "comment"

DB-1916: more accurate removing activity-stream

---

l10n/de/browser/chrome/browser/migration/migration.dtd
l10n/de/browser/chrome/browser/migration/migration.properties
mozilla-release/browser/base/content/browser-addons.js
mozilla-release/browser/base/content/browser-menubar.inc
mozilla-release/browser/base/content/browser-sets.inc
mozilla-release/browser/branding/cliqz/pref/firefox-branding.js
mozilla-release/browser/components/customizableui/CustomizableWidgets.jsm
mozilla-release/browser/components/customizableui/content/panelUI.inc.xul
mozilla-release/browser/components/migration/FirefoxProfileMigrator.js
mozilla-release/browser/components/migration/MigrationUtils.jsm
mozilla-release/browser/components/migration/content/migration.js
mozilla-release/browser/components/migration/content/migration.xul
mozilla-release/browser/components/migration/nsIBrowserProfileMigrator.idl
mozilla-release/browser/locales/en-US/chrome/browser/browser.properties
mozilla-release/browser/locales/en-US/chrome/browser/migration/migration.dtd
mozilla-release/browser/locales/en-US/chrome/browser/migration/migration.properties
mozilla-release/devtools/client/aboutdebugging/components/addons/Panel.js
mozilla-release/testing/marionette/addon.js
mozilla-release/toolkit/mozapps/extensions/AddonManager.jsm
mozilla-release/toolkit/mozapps/extensions/content/extensions.js
mozilla-release/toolkit/mozapps/extensions/content/extensions.xul
mozilla-release/toolkit/mozapps/extensions/internal/XPIInstall.jsm

Feature to let user import addons from FIrefox to Cliqz.

Importing addons

---

mozilla-release/toolkit/mozapps/extensions/content/extensions.js
mozilla-release/toolkit/mozapps/extensions/content/extensions.xul

Removes empty notice when no addon, also removes installed addons heading when no addon.

DB-1897: removing empty notice when no addon

---

mozilla-release/browser/components/moz.build
mozilla-release/browser/components/nsBrowserContentHandler.js
mozilla-release/browser/components/sessionstore/SessionStartup.jsm
mozilla-release/browser/components/sessionstore/content/aboutSessionRestore.js
mozilla-release/browser/modules/HomePage.jsm

DB-1929: fixed opening a blank tab at the browser startup

---

mozilla-release/browser/components/nsBrowserGlue.js

@alver-cliqz @luciancor @tsl143

DB-1930: deactivated Weave service in nsBrowserGlue

---

l10n/de/browser/chrome/browser/browser.properties
mozilla-release/browser/locales/en-US/chrome/browser/browser.properties

DB-1931: improve some descriptions and DE localization

---

l10n/de/browser/chrome/browser/preferences/cliqzpref.dtd
mozilla-release/browser/components/extensions/parent/ext-tabs.js
mozilla-release/browser/components/preferences/in-content/privacy.xul
mozilla-release/browser/locales/en-US/chrome/browser/preferences/cliqzpref.dtd
mozilla-release/browser/locales/en-US/chrome/browser/preferences/privacy.dtd
mozilla-release/toolkit/modules/PrivateBrowsingUtils.jsm

Also adding strings from DB-1938

DB-1936: allowing containers along with AFT

---

mozilla-release/browser/components/newtab/lib/ASRouterPreferences.jsm
mozilla-release/browser/components/preferences/in-content/main.js
mozilla-release/browser/components/preferences/in-content/main.xul

DB-1946: removed firefox recommendations

---

l10n/de/browser/chrome/browser/preferences/cliqzpref.dtd
l10n/de/toolkit/chrome/mozapps/extensions/extensions.dtd
l10n/de/toolkit/chrome/mozapps/extensions/extensions.properties
mozilla-release/toolkit/mozapps/extensions/content/extensions.js
mozilla-release/toolkit/mozapps/extensions/internal/AddonRepository.jsm

Changes the way we get latest install url of addons from AMO and get and text change

DB-1949: quick fix

---

mozilla-release/browser/base/content/browser.js
mozilla-release/browser/components/CliqzResources.jsm
mozilla-release/browser/components/extensions/parent/ext-url-overrides.js

@alver-cliqz @luciancor @tsl143

DB-1954: fixed addon installation

---

mozilla-release/browser/components/build/nsModule.cpp
mozilla-release/browser/components/migration/FirefoxProfileMigrator.js
mozilla-release/browser/components/migration/moz.build
mozilla-release/browser/components/migration/nsFirefoxPasswordMigrator.cpp
mozilla-release/browser/components/migration/nsFirefoxPasswordMigrator.h
mozilla-release/browser/components/migration/nsIFirefoxPasswordMigrator.idl
mozilla-release/toolkit/xre/MigratePwdFirefox.cpp
mozilla-release/toolkit/xre/moz.build
mozilla-release/toolkit/xre/nsAppRunner.cpp
mozilla-release/toolkit/xre/nsAppRunner.h

Windows only, without master password. Working with master password need more accurate solution

DB-1658: migrate passwords from Firefox with importing

---

mozilla-release/browser/base/content/browser.js
mozilla-release/browser/components/CliqzResources.jsm

cliqz-homepage-fix1: fixed determination of webextension API

---

mozilla-release/browser/base/content/browser.js

cliqz-homepage-fix_3: load uri asynchronously the very 1st time

---

mozilla-release/browser/themes/osx/cliqz/theme.css
mozilla-release/browser/themes/windows/cliqz/theme.css

DB-1955: low contrast between active and non-active tabs

---

mozilla-release/browser/themes/linux/cliqz/theme.css
mozilla-release/browser/themes/osx/cliqz/theme.css
mozilla-release/browser/themes/windows/cliqz/theme.css

@luciancor @alver-cliqz @tsl143

DB-1961: add new tab button hover fixed

---

mozilla-release/browser/themes/osx/cliqz/theme.css

DB-1974: remove extra space before the first tab

---

mozilla-release/browser/themes/linux/cliqz/theme.css
mozilla-release/browser/themes/osx/cliqz/theme.css
mozilla-release/browser/themes/windows/cliqz/theme.css

DB-1975: url bar stays grey while being inactive

---

mozilla-release/browser/themes/linux/cliqz/theme.css

DB-1980: not enough contrast between active and inactive tabs (linux) - fixed

---

mozilla-release/browser/components/AutoForgetTabsService.js

In next version will be better solution for using the latest bloom filter file.

DB-1973: remove using from extension bloom filter file for AFT

---

mozilla-release/browser/base/content/browser.xul

Hiding manage extension and remove button for page actions

DB-1998_2: cliqz extension disable or uninstall forbidden

---

mozilla-release/browser/installer/windows/nsis/installer.nsi

plus some minor NSIS installer fixes

DB-2019: remove new SendPing signal for silent installation

---

mozilla-release/browser/components/customizableui/CustomizableUI.jsm

retain browser action for cliqz and myoffrz on restore to defaults

DB-2005: retain browser action for cliqz and myoffrz

---

mozilla-release/browser/base/content/browser-siteIdentity.js

DB-2020: Freshtab override issue

DB-2020: Freshtab override issue

---

cliqz.cfg
mozilla-release/browser/app/profile/firefox.js

DB-2005: Fixing the new profile issue for browser action positions

DB-2005: Fixing the new profile issue for browser action positions

---

mozilla-release/browser/base/content/browser-siteIdentity.js
mozilla-release/browser/components/preferences/in-content/main.js

DB-2014: Remove language switch

DB-2014: Remove language switch

---

mozilla-release/config/rules.mk

This reverts commit 9c9f2be798c8161c217a8cf71451ecaa445bf78b.

Revert "Revert "Update onionmodexpi and Tor artifacts""

---

mozilla-release/toolkit/actors/WebNavigationChild.jsm

`setTimeout` only in case of error and if its from moz-extension

DB-1991: Fixing blank tab issue

---

Jenkinsfile
Jenkinsfile.macoslinux.crossbuild
Jenkinsfile.release
cliqz_env.sh
docker/Dockerfile
docker/Dockerfile.osxcross
docker/get_osxcross_deps.sh
magic_build_and_package.sh
magic_upload_files.sh
mozilla-release/browser/config/cliqz-release-cross.mozconfig
mozilla-release/browser/config/cliqz-release.mozconfig
upload_macoscross.sh

Build Browser for OSX on Linux

DB-1669 Osxcrossbuild

---

Jenkinsfile.release

1. Use email-lists instead of real emails
2. Do not publish MacOS cross build yet to Balrog
3. Upload beta linux tar.bz2 to beta/latest

Fix CI script:

---

Jenkinsfile.macoslinux.crossbuild

Fetch proper repo for signing step

---

mozilla-release/toolkit/locales/en-US/toolkit/about/aboutAddons.ftl
mozilla-release/toolkit/mozapps/extensions/content/extensions.js
mozilla-release/toolkit/mozapps/extensions/content/extensions.xul

DB-2084: nit pick

---

mozilla-release/toolkit/mozapps/extensions/internal/XPIDatabase.jsm

DB-1990: Disallow non signed system addons from install location

---

mozilla-release/security/apps/AppSignatureVerification.cpp
mozilla-release/toolkit/mozapps/extensions/internal/XPIProvider.jsm

Original issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1548973

Critical fix for Mozilla signed addons

---

mozilla-release/browser/components/migration/ChromeProfileMigrator.jsm

Renaming field names as per chrome DB

DB-2130: fix cookie import

---

mozilla-release/browser/themes/osx/browser.css

Restoring #1306  and fixing URLbar shadow issue

DB-2237: fixing URLbar issue

---

mozilla-release/browser/base/content/browser-places.js

DB-2244: fixing bookmark issue and removing bookmark recommendation served from activity stream

DB-2244: fixing bookmark issue and removing bookmark recommendation

---

mozilla-release/browser/components/urlbar/UrlbarInput.jsm

Avoid adding controller to (quantam) urlbar as its hijacked anyway by extension

DB-2229: fix exception with urlbar controller

---

mozilla-release/toolkit/mozapps/extensions/AddonManager.jsm

This is repetition.
We did this fix in Cliqz and then PR was also merged in FF for same.

72 merge letfovers

---

mozilla-release/browser/components/urlbar/UrlbarInput.jsm

With this check
Without this check

DB-2378: fixing moz-ext URL in url bar

---

mozilla-release/browser/components/search/extensions/qwant/_locales/de/messages.json
mozilla-release/browser/components/search/extensions/qwant/_locales/en/messages.json

See https://searchfox.org/mozilla-central/source/browser/components/search/extensions/qwant/manifest.json#20

Update Qwant search engine name

---

sign_lin.sh

Based on: https://superuser.com/a/1327486

linux: fix signing with gpg

---

mozilla-release/browser/components/sessionstore/SessionStore.jsm

We still need to take care of 2 blank tabs in the start. This is to check update on beta channel

DB-2435: fixing tabs[0] undefined issue

---

l10n/de/browser/chrome/browser/browser.dtd
mozilla-release/browser/components/BrowserGlue.jsm
mozilla-release/browser/components/customizableui/content/panelUI.inc.xhtml
mozilla-release/browser/components/customizableui/content/panelUI.js
mozilla-release/browser/locales/en-US/chrome/browser/browser.dtd
mozilla-release/browser/themes/shared/customizableui/panelUI.inc.css

DB-2469: remove Show enabled addon notification
