cliqz.cfg, mozilla-release/toolkit/mozapps/extensions/content/extensions.css
For debugging purposes we add a pref:
`extensions.cliqz.listed` that control extension visibility on addons
list. On pref change restart is required.
=> Configuration: CLIQZ visiblility based on pref

mozilla-release/browser/components/shell/nsWindowsShellService.cpp
When trying to set browser default in Win10 let's show system dialog "open with" instead of open Settings menu.
Original FF had this in 40-th version, so for now we just turn it on back in our build.
Commit in original FF: https://hg.mozilla.org/mozilla-central/rev/03f47dc4ada5
We need our own webpage with info, how to set browser default in Win10. Now if user choose another browser in list - this selected browser will open https://support.mozilla.org/1/firefox/43.0.3/WINNT/en-US/win-10-default-browser (which doesn't exist). We can use https://support.mozilla.org/en-US/kb/how-change-your-default-browser-windows-10 as template for such webpage.
=> BROWSER-75: on Win10 show "openas" dialog

cliqz.cfg
In case CLIQZ extension is outdated or not-present, autoconfig should install it before browser open first window. 
Most important use case is to update to signed extension if browser requires XPI signing.
=> Autoconfig: install CLIQZ extension on startup

cliqz.cfg
Entire feature is just a dirty hack. Autoconfig should not rely on
extension APIs as we cannot guarantee those will not change over time.
We should move entire feature into Firefox codebase.
Fixing: #130
=> Quickfix: help menu - createQbutton API change

inject_tag_info.bat
It's better to setup this variable outside the script (Windows installer of Go by default add it)
=> BROWSER-108: GOROOT variable must be setup with environment variables

magic_build_and_package.sh
Fix argument parser (--clobber should now work).
=> DB-98: Fixed bug in magic build script argument parser

mozilla-release/configure.in
It's look like possible to use two different ways to set up a locale for building - MOZ_UI_LOCALE environment variable or with mozconfig file with --enable-ui-locale option. In real - MOZ_UI_LOCALE always set up in configure.in, so it's only one way to change it - with mozconfig file. Which looks wrong. Here we make changes in configure.in script so now it's possible to set up language correctly in both different way.
ps. looks like js/src/configure.in have similar problem, but it don't used in our build now
pps. may be we can push this commit to original FF
=> DB-98: fix bug in FF configuration script with locale processing

cliqz.cfg, mozilla-release/browser/branding/cliqz/locales/browserconfig.properties
This preference default value is already set in `browser/app/profile/firefox.js`, value is taken from browserconfig.properties.
=> DB-365: Homepage preference is reset after restart

sign_win.bat
Now works with all *.exe and *.dll files in installer. Also check does file have been signed before or not. And fix an error handling (work with ERRORLEVEL in windows batch script is tricky, https://support.microsoft.com/en-us/kb/39585)
=> DB-372: improve digital signing script on Windows

sign_win.bat
Binaries must be signed twice - with sha1 and sha256 (for normal work on WinXP SP3 and Win10)
=> DB-372: make DualSigning on windows

mozilla-release/browser/components/sessionstore/SessionStore.jsm
When we deduplicated tabs to avoid multiple start pages, we looked at
first url in tab's navigation chain. Instead, we should look at the
one user finished with (usually last in the chain), or the last one.
=> DB-396: Fixed tab restore deduplication

mozilla-release/toolkit/mozapps/extensions/content/extensions.xul
Probably was introduced by the recent rewrite of git history.
=> DB-410: Duplicate notification line on addons internal page

magic_upload_files.sh
We incorrectly run entire automation/build while only upload step was required. 
Not really sure why it was working before.
=> Build fix: mac universal builds upload signed version

cliqz_env.sh, magic_build_and_package.sh, magic_upload_files.sh
For developers convinience we can just:
`source cliqz_env.sh`
to have all environment variables set.
=> Build: Encapsulating shared part of magic scripts

cliqz.cfg, mozilla-release/browser/config/cliqz-release.mozconfig, mozilla-release/modules/libpref/init/all.js, mozilla-release/toolkit/components/telemetry/Telemetry.cpp, mozilla-release/toolkit/components/telemetry/TelemetryController.jsm, mozilla-release/toolkit/mozapps/extensions/internal/XPIProvider.jsm, mozilla-release/toolkit/mozapps/extensions/internal/XPIProviderUtils.js
Allow  unsigned dictionaries as they should be harmless.
Verify addons signatures on every startup synchronously.
Report addons installation attempts to own telemetry server.
=> DB-530: Better addons blocking

mozilla-release/browser/components/shell/nsWindowsShellService.cpp
On settings screen for Win10
Commit in FF: https://hg.mozilla.org/mozilla-central/rev/89a9d2c4edf4, we need it early then FF47
=> DB-75: Scroll "Default apps" into the default browser option

magic_build_and_package.sh, mozilla-release/browser/app/profile/firefox.js
Imlements: https://cliqztix.atlassian.net/browse/DB-488?jql=text%20~%20%22geolocation%22
Should not be merge until build servers will provide MOZ_MOZILLA_API_KEY as environment variable.
=> DB-488: builds expect MOZILLA_API_KEY

mozilla-release/browser/components/shell/nsWindowsShellService.cpp
Returning back to normal, proper way to set default browser in Win10 (same as in original FF)
=> DB-75: remove experiment with setting as default in Win10 with protocol redefining.

mozilla-release/browser/installer/windows/nsis/installer.nsi, mozilla-release/browser/installer/windows/nsis/uninstaller.nsi
Do not delete this file while installing over already existing version
=> DB-379: delete distribution.js file on uninstall only.

mozilla-release/toolkit/mozapps/extensions/internal/XPIProvider.jsm
It will fail in nearly 100% of cases, because there's only 1 extension
with acceptable signature in a whole world anyway.
=> DB-556: Don't check updates for unsigned extensions.

l10n/de/browser/chrome/overrides/netError.dtd, mozilla-release/browser/locales/en-US/chrome/overrides/netError.dtd, mozilla-release/netwerk/base/security-prefs.js
Reverts cliqz-oss/browser-f#277
Reverting this PR as our backend seems to be broken for now. Moving it to next release
=> Revert "SSL Error Reporting service + update messaging"

cliqz_env.sh, magic_build_and_package.sh, magic_upload_files.sh, mozilla-release/config/rules.mk, mozilla-release/tools/update-packaging/Makefile.in, sign_win.bat
To be able to build DE build please set up CQZ_BUILD_LOCALIZATION env variable (any value)
Language repack could be done in 3 steps (on Windows):
1. Build an installer first (based on en-US installer)
2. Sign the installer (similar as en-US)
3. Create .complete.mar update package
I tried to support old a new build process. To use new way to publish and use artifacts - please use CQZ_BUILD_ID
=> DB-549: Create DE build as Localization Repack

mozilla-release/browser/config/cliqz-release.mozconfig, mozilla-release/toolkit/mozapps/installer/linux/rpm/mozilla.spec
* remove --enable-warnings-as-errors from Linux build
* fix --disable-tests flag processing (http://backreference.org/2011/09/17/some-tips-on-rpm-conditional-macros/) - this patch could be send to Mozilla
=> DB-37: fix Linux build

mozilla-release/browser/app/Makefile.in
Use CFBundleSignature value to write into PkgInfo
=> DB-642: Fix apple bundle PkgInfo

cliqz_env.sh, magic_build_and_package.sh, magic_upload_files.sh, mozilla-release/toolkit/mozapps/installer/package-name.mk, sign_win.bat
CQZ_BUILD_ID. It is hard to totally replace FF "buildid" because it spread all over the build scripts and expected exactly in format "%Y%m%d%H%M%S". We need to use same format in our build. Jenkins must generate environment variable CQZ_BUILD_ID (or can be set up manually on dev environment)
CQZ_BUILD_DE_LOCALIZATION. Optional, must be set up if we need in DE build (build with language repack)
=> DB-666: some improvement for new build system

mozilla-release/config/rules.mk
=> Bump extension version to 1.9.2 (fixes Firefox 49 incompatibility)

mozilla-release/browser/config/cliqz-release.mozconfig
Due to changes in mozilla-release\build\moz.configure\init.configure parameter --enable-update-channel must be specified
=> DB-902: fix update channel information

mozilla-release/browser/base/content/tabbrowser.xml, mozilla-release/browser/components/sessionstore/SessionStore.jsm
Use "private" attribute of contextTab for duplicated Tab
=> DB-919: Duplicated Tab is not in Forget Mode

mozilla-release/config/rules.mk
@alver-cliqz can we please have a new version 1.8.1 of the browser containing this update?
=> DB-970: update extension to 1.10.0

mozilla-release/browser/components/sessionstore/SessionStore.jsm
Was broken in #409
Restoring original fix from #412
=> DB-731: Restore Session Tab should be opened by default in case browser was crashed

mozilla-release/testing/profiles/prefs_general.js
Do not show onboarding from CLIQZ extension on build process only
=> DB-993: fix PGO build

mozilla-release/browser/extensions/moz.build
Based on https://bugzilla.mozilla.org/show_bug.cgi?id=1311515 it still not good plus we can not use it properly
=> DB-1070: remove aushelper extension from CLIQZ browser

mozilla-release/toolkit/components/url-classifier/SafeBrowsing.jsm
Cliqz doesn't use urlclassifier.trackingTable and urlclassifier.trackingWhitelistTable
=> DB-1067: fix error in SafeBrowsing lists processing

mozilla-release/browser/components/AutoForgetTabsService.js, mozilla-release/toolkit/components/telemetry/Histograms.json
What we measure:
- number of times the Auto Forget Tab notification was displayed
- number of times user picked "Reload in Normal Mode"
- number of times user picked "Always load in Normal Mode"
- number of times user picked "Change Settings"
@maxim-cliqz, @luciancor: that's my first piece of code in JS, so I'd appreciate a review :)
=> DB-799: Add signals for Auto Forget Mode to Browser Telemetry

cliqz_env.sh
Our CQZ_RELEASE_CHANNEL used in lightly different way and can not be just directly copied to MOZ_UPDATE_CHANNEL. From now, be default MOZ_UPDATE_CHANNEL always setup as 'beta' channel, except release build (when CQZ_RELEASE_CHANNEL == release)
=> DB-1169: change way how to setup MOZ_UPDATE_CHANNEL

mozilla-release/browser/base/content/aboutDialog.js, mozilla-release/browser/base/content/aboutDialog.xul
We don't use "version" element on About dialog in CLIQZ browser.
=> DB-1200: fix problem with updater on About dialog.

mozilla-release/browser/installer/package-manifest.in, mozilla-release/browser/installer/removed-files.in, mozilla-release/config/createprecomplete.py, mozilla-release/toolkit/mozapps/installer/packager.mk
We still need in this file (C++ code checking for it present to launch some plugins). There no easy way to generate normal file with gen-eme-voucher.py (problem with macholib library).
=> DB-1215: workaround for voucher.bin

build_win.bat, magic_build_and_package.sh, mozilla-release/browser/config/cliqz-release.mozconfig
This environment variables doesn't supported anymore.
This keys must be defined with build flags:
--with-mozilla-api-keyfile
--with-google-api-keyfile
=> DB-1237: CQZ_GOOGLE_API_KEY and MOZ_MOZILLA_API_KEY

mozilla-release/browser/installer/package-manifest.in, mozilla-release/browser/installer/removed-files.in, mozilla-release/config/createprecomplete.py, mozilla-release/toolkit/mozapps/installer/packager.mk
This reverts commit bdca44e5133afad1d4836a88c39b5e7e291d4211.
Doesn't work as expected (in version FF 52). Need to re-research for solution
=> Revert "DB-1215: workaround for voucher.bin"

mozilla-release/devtools/client/aboutdebugging/components/aboutdebugging.js, mozilla-release/devtools/client/aboutdebugging/components/moz.build, mozilla-release/devtools/client/jar.mn
From about:debugging page. This page will be available only for non-release builds. I think in this task a good idea to remove this page totally, not only "hide" it.
=> DB-1276: remove addons section for release build

Jenkinsfile
rust was missing during the build phase even though it was installed by bootstrap.py. Now we ensure we run scripts in a login shell, so both bashrc and profile are sourced.
=> CI: fixes for linux

cliqz.cfg
This information disappear because we removed distribution.ini file. Now put part of information to cliqz.cfg file.
Related to DB-1353 ticket, removing distribution.ini.
Checked update - it works normally with "Cliqz" as product name.
=> DB-1366: fix information on About dialog

mozilla-release/browser/installer/windows/nsis/installer.nsi, mozilla-release/browser/installer/windows/nsis/shared.nsh
For Win8/Win10, on update and upgrade (install on top of previous version).
Also sent a patch to Mozilla (https://bugzilla.mozilla.org/show_bug.cgi?id=1378142)
=> DB-1370: more accurate way to update tile on Start Menu screen

mozilla-release/browser/base/content/tabbrowser.xml
Remove a code, same as in original FF 54.0
=> DB-1404: fix linkedBrowser "We're in trouble" message.

mozilla-release/browser/components/sessionstore/SessionStore.jsm
Firefox 55 change a way how they works with restored tabs. Looks like they are not normally initialized as web page at start time. SessionSaver trying to save all tabs. In debugger we moved down to "_collectWindowData: function ssi_collectWindowData(aWindow)", where get an error in condition "if (tab.private)". This is our getter/setter, which was add by Max many versions ago (to track private tab). And now it do not work because loadContext do not created for restored tabs, until they became active (focused). For now we can remove this code, because private tabs will be filtered later in SessionSaver, _saveState function, PrivacyFilter.filterPrivateWindowsAndTabs(state).
In next version we need to review code with our getter/setter private (in tabbrowser.xml)
=> DB-1445: fix tab restoring after browser restart

mozilla-release/browser/components/about/AboutRedirector.cpp
about:home is not capable to run new tab page, the about:cliqz is doing a redirect to the proper page
=> fix: about:home shoudl redirect to about:cliqz

Dockerfile
Fix for rust installation. 
Also, bootstrap.py tries to install apt packages that responds with 404. 
Quick and dirty solution
=> Rust installation fix and some apt preparation

Dockerfile
Upgraded Rustup version to 1.7.0
Explicitly install the right toolchain and set as default
=> Fixed rust issues with linux build

mozilla-release/browser/config/cliqz.mozconfig
as all addons have to be super signed, allowing legacy extensions is just a way for Cliqz developers to debug `browser-core`
=> Allowing legacy extensions

l10n/de/browser/chrome/browser/preferences/preferences.properties, l10n/de/browser/chrome/browser/preferences/search.dtd, mozilla-release/browser/components/preferences/in-content/privacy.js, mozilla-release/browser/components/preferences/in-content/privacy.xul, mozilla-release/browser/locales/en-US/chrome/browser/preferences/preferences.properties, mozilla-release/toolkit/components/extensions/NativeManifests.jsm
DB-1571: Settings "Learn more" link for HTTPS everywhere is not inline
DB-1573: Remove inactive button in settings to allow websites to install addons
DB-1576: On the page 'about:preferences#connect' there is extra info about HTTPS
DB-1572: In 'Suchergebnisse' in preferences the space between words is missing
DB-1550: Localization
=> DB-1550, DB-1571, DB-1572, DB-1573, DB-1576

mozilla-release/browser/base/content/browser.xul
=> DB-1617: remove duplicate "duplicate tab" option from tab context menu

mozilla-release/toolkit/components/telemetry/TelemetryEnvironment.jsm
Add `network.cookie.cookieBehavior` to default environment prefs in browser telemetry.
@luciancor
=> Record the cookie behavior preference in browser telemetry

Jenkinsfile.release, Jenkinsfile.win, build_win.bat, cliqz_env.sh, inject_tag_info.bat, magic_build_and_package.sh, magic_upload_files.sh, mozilla-release/browser/config/cliqz-release-64.mozconfig, mozilla-release/build/gen_build_properties.py, mozilla-release/config/rules.mk, sign_win.bat
1. Remove outdated stuff
2. Add support for 64-bit build on Windows
From now it's possible just to start build_win.bat (Windows) or magic_build_and_package.sh (MacOS, Linux) to build a project with default settings (no needs to specify any variable)
=> DB-1335, DB-1564: improve build scripts

mozilla-release/browser/config/cliqz-release.mozconfig
This reverts commit 17b976cd407d3f76ac464f36515c670bd8b141f4.
Need more investigation before using in our build. Using stylo increase a build time on Windows and make impossible to generate build symbols on Mac.
=> Revert "Enable Stylo (#819)"

mozilla-release/browser/config/cliqz-release.mozconfig
This reverts commit 4b284bdd4a7136daa9cbb20553ab640037518380.
We can not build browser on Mac with buildsymbols. Rust version 1.21. dsymutil fall to segmentation fault. FF building Mac version on Linux with cross compiling, they also faced with same problem, it's not possible to gather buildsymbols from code, generated by Rust. Will try to fix this issue later (with minor update probably). Now we need a release build
=> Revert "DB-1649: enable stylo (#829)"

mozilla-release/toolkit/components/telemetry/TelemetryEnvironment.jsm
Add `browser.uidensity` to recorded prefs.
cc @oleksandra-cliqz @luciancor
=> DB-1662: Add the density pref to telemetry environment

mozilla-release/browser/themes/linux/jar.mn
Fixes broken security popup UI in linux.
Tested locally, archlinux, x86_64 Linux 4.14.20
FIXES: DB-1553
=> DB-1553: Enables preproccesing for panel.css for linux builds.

mozilla-release/browser/base/content/urlbarBindings.xml
Backported firefox fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1434045
=> DB-1674: avoid errors when XBL destructors fire without the constructor having fired

mozilla-release/browser/components/AutoForgetTabsService.js
Problem was in nsChromeProtocolHandler.cpp, checking for NS_ENSURE_ARG_POINTER(aLoadInfo) was add in FF 56
=> DB-1625: use adultlist from extension again

mozilla-release/browser/app/profile/firefox.js
This default behavior was initially changed to prevent a 16-years old
bug in SeaMonkey, which was already fixed in Firefox since 2007. See
following issues for more details:
* https://bugzilla.mozilla.org/show_bug.cgi?id=190615
* https://bugzilla.mozilla.org/show_bug.cgi?id=611162
This has been tested in the following way:
- Build from source on Ubuntu 16.04
- Tested artifact on Ubuntu and made sure that the behavior is consistent with MacOs
=> Unify behavior of urlbar selection on click and double-click for Unix.

mozilla-release/toolkit/mozapps/extensions/content/extensions.js, mozilla-release/toolkit/mozapps/extensions/content/extensions.xul
Please count that in Cliqz browser legacy extension still enabled by default
=> DB-1763: remove legacy extension page from about:addons

Jenkinsfile, Jenkinsfile.release, mozilla-release/config/rules.mk
This reverts commit 9aeca5aa6298a3211974a4aad1bdd8e9dbbd644d.
We don't need it now because we can install it for users with usual SystemAddons update process. Will need it later, after final version of Consentric will be released.
=> DB-1812: Revert "add template Consentric SystemAddon"

mozilla-release/browser/components/preferences/in-content/preferences.js, mozilla-release/browser/components/preferences/in-content/privacy.js
When scrolling, do not wait for `formAutofillParent` (as it is disabled in Cliqz), wait for `gPasswordManagers` and `gPrivacyManagers` initialization instead.
=> DB-1809: fix scrolling to Data Collection section

mozilla-release/browser/locales/search/list.json
Sorry @alver-cliqz, got a new request from @oleksandra-cliqz to move the Cliqz search after Yahoo.
=> DB-1767: Move Cliqz search to the 3rd position below Yahoo

mozilla-release/toolkit/xre/nsAppRunner.cpp
This prevents upgrades being installed when opening Tor Mode (env variable MOZ_CLIQZ_SKIP_UPDATES).
=> [Tor] Allow skipping updates at startup via env variable

mozilla-release/netwerk/dns/nsDNSService2.cpp
This should only disable DNS service if proxy is set to manual AND "proxy DNS through SOCKS" setting is enabled. Right now only the latter is checked.
=> Only disable DNS if proxy settings is set to manual

mozilla-release/browser/themes/linux/cliqz/theme.css, mozilla-release/browser/themes/osx/cliqz/theme.css, mozilla-release/browser/themes/windows/cliqz/theme.css
This is what ui/window module is setting for each window. @luciancor @mai-cliqz Is this ok? Or should this be in a common css instead of one for each platform?
=> DB-1858: Move urlbar style changes from ui/window.es to browser theme

cliqz.cfg
AMO uses `window.navigator.mozAddonManager` to handle addon installs/remove in Firefox. This leads to handling of failure messages by AMO not Firefox. Disabling `mozAddonManager` restores the native behaviour of browser on AMO, and failure messages are displayed as before.
=> Fix | download failed message on AMO - prevent mozaddonmanager

cliqz.cfg
Change default cookie behavior to block storage APIs for trackers by default. Tracking-protection UIs remain disabled.
@alver-cliqz @luciancor @remusao
=> Enable anti-tracking cookie storage policy by default

mozilla-release/toolkit/components/extensions/child/ext-runtime.js, mozilla-release/toolkit/components/extensions/schemas/runtime.json
We need to expose a flag if browser is cliqz in runtime API.
This will be (majorly) consumed by Ghostery extension
=> DB-1926: extending runtime API to include isCliqz

mozilla-release/browser/components/migration/FirefoxProfileMigrator.js
Firefox introduced another parameter in `Services.cookies.add` function
=> DB-1915: fixing cookie import erport errors

mozilla-release/config/rules.mk
- Update Tor artifacts from Tor Browser 8.0.5.
- Update onionmode to 0.0.6 (minor bug fixing).
- Add hash verification for Tor artifacts and onionmode xpi.
=> Update onionmode xpi and Tor artifacts

mozilla-release/browser/components/sessionstore/SessionStore.jsm
This fix prevents focus to go to browser content in case of delayed startup(for Cliqz its case for every freshtab)
=> DB-2042: URL Bar focus issue

mozilla-release/config/rules.mk
Adds the prototype dat extension as a system addon at build time. We will test this extension on the beta channel.
I've guessed from the other system addons how to do this, please let me know if other steps are required.
cc @chrmod
=> Add Dat extension as system addon

mozilla-release/toolkit/mozapps/extensions/content/extensions.js
Due to border of permission box now, it is fairly visible in details section of plugin, dictionaries,languages too.
We need to get rid of them.
=> DB-2048_2 prevent permission box border on detailed pages of plugin/dictionary etc

build_win.bat, mozilla-release/browser/config/cliqz-release.mozconfig
This is fix for Firefox 66.0 only, must be removed after merging with Firefox 67.0
=> DB-2101: fix for build with MSVC on Windows

mozilla-release/browser/components/preferences/in-content/main.xul, mozilla-release/browser/components/preferences/in-content/privacy.xul, mozilla-release/browser/themes/shared/incontentprefs/preferences.inc.css
This is a known issue for Firefox and for some reason is not prioritized and eventually not fixed.
https://bugzilla.mozilla.org/show_bug.cgi?id=1202492
PS: the wrong indentation of checkbox in code is intentional - to avoid conflicts
=> DB-2128: fixing checkbox and radio box width to improve click behaviour

cliqz.cfg
Before 1.24 Cliqz did not allow installation of addons, so we did not require `mozaddonmanager` and it caused issues when one opens addons.mozilla.org (see DB-1879) 
from 1.24 we allowed installation of Mozilla signed addon, now we must include mozaddonmanager in order to streamline installation and avoid third party website warning.
=> DB-2142: preventing third party website warning(enabling mozaddonmanager

mozilla-release/toolkit/mozapps/extensions/Blocklist.jsm
This PR ensures no system addon can be disabled by blocklist.
We maintain list/update of system addon and we know we never want to block any system addon.
=> DB-2218: exempt system addons from blocklist

mozilla-release/browser/base/content/PrivateTabUI.jsm, mozilla-release/browser/base/content/browser.js, mozilla-release/browser/base/content/tabbrowser.js, mozilla-release/browser/base/content/utilityOverlay.js, mozilla-release/browser/components/extensions/parent/ext-browser.js, mozilla-release/browser/components/sessionstore/SessionStore.jsm
In this PR I added a "private" attribute for a tab xul element.
Whenever the extension requests a status of a tab first we check whether the tab has contents loaded into that (linkedBrowser.loadContext is not null). If it does not then we rely on the "private" attribute value. Otherwise we define privacy on linkedBrowser.loadContext.
=> DB-2208: added a private attribute for tabs

mozilla-release/browser/base/content/browser-contentblocking.js, mozilla-release/browser/base/content/browser.js, mozilla-release/browser/base/content/nsContextMenu.js, mozilla-release/browser/base/content/tabbrowser.js, mozilla-release/browser/components/extensions/parent/ext-browser.js, mozilla-release/browser/components/extensions/parent/ext-find.js, mozilla-release/browser/components/extensions/parent/ext-menus.js, mozilla-release/browser/components/extensions/parent/ext-tabs.js, mozilla-release/browser/components/extensions/parent/ext-windows.js, mozilla-release/browser/components/newtab/lib/BookmarkPanelHub.jsm, mozilla-release/browser/components/places/PlacesUIUtils.jsm, mozilla-release/browser/modules/ContentSearch.jsm, mozilla-release/browser/modules/PermissionUI.jsm, mozilla-release/browser/modules/webrtcUI.jsm, mozilla-release/toolkit/components/extensions/parent/ext-tabs-base.js, mozilla-release/toolkit/components/passwordmgr/LoginManagerParent.jsm, mozilla-release/toolkit/components/remotebrowserutils/RemoteWebNavigation.jsm, mozilla-release/toolkit/components/thumbnails/PageThumbs.jsm, mozilla-release/toolkit/components/viewsource/content/viewSourceUtils.js, mozilla-release/toolkit/modules/PrivateBrowsingUtils.jsm
In this PR I have added a new method "isTabContextPrivate" to PrivateBrowsingUtils module.
The method receives a tab as the first argument and a boolean flag (fromContainer) as the second.
First we try to access the tab's linkedBrowser. If it is null then rely on a value of tab's "private" attribute. Else we examine whether aTab.linkedBrowser has a loadContext, meaning page contents displayed in a window. If it is not there (== null) then rely on the tab's "private" attribute value again.
Otherwise isTabContextPrivate method falls back to isBrowserPrivate implementation.
=> DB-2234: add tab privacy check | fixed loadContext error

l10n/de/browser/browser/preferences/preferences.ftl, l10n/de/browser/chrome/browser/browser.properties, l10n/de/browser/chrome/browser/cliqzPrivateBrowsing.dtd, mozilla-release/browser/app/profile/firefox.js, mozilla-release/browser/components/BrowserGlue.jsm, mozilla-release/browser/components/preferences/in-content/privacy.inc.xul, mozilla-release/browser/components/privatebrowsing/content-cliqz/aboutPrivateBrowsing.css, mozilla-release/browser/components/privatebrowsing/content-cliqz/aboutPrivateBrowsing.js, mozilla-release/browser/components/privatebrowsing/content-cliqz/aboutPrivateBrowsing.xhtml, mozilla-release/browser/components/privatebrowsing/jar.mn, mozilla-release/browser/locales/en-US/browser/preferences/preferences.ftl, mozilla-release/browser/locales/en-US/chrome/browser/cliqzPrivateBrowsing.dtd
This fixes, 
1. DE translations
2. `about:privatebrowsing` opened in normal window was showing forget mode
3. turn on AFW by default for new users. (still need to remove AB tests)
=> DB-2319: AFW translation, about:privatebrowsing

mozilla-release/browser/components/BrowserGlue.jsm, mozilla-release/toolkit/mozapps/extensions/internal/XPIInstall.jsm, mozilla-release/toolkit/mozapps/extensions/internal/XPIProvider.jsm
THis patch makes sure that addon packed with browser atleast gets checked against current installed version of system addon.
=> DB-2338: improving system addon update

mozilla-release/browser/components/preferences/in-content/main.inc.xul
Putting back hidden true, FF deals all the `groupbox` hide/show by `data-category` attribute
so lets go FF way
=> DB-2342: hiding language heading at other pages

mozilla-release/browser/app/profile/firefox.js
As discussed with @tsl143 , the reject tracker policy is currently not working properly as the tracking protection code has been removed. This change switches to a more protective default until we can implement a reject tracker policy using our own tracking list.
=> Update default cookie policy to reject from unvisited

cliqz.cfg
Firefox already uses max 8 process, so we do not need to restrict this to 4
here - https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/modules/libpref/init/all.js#L2673
=> falling back to processcount 8 as Firefox

mozilla-release/browser/app/profile/firefox.js
Changes referer policy for cross-origin requests (see [this page](https://wiki.mozilla.org/Security/Referrer) for description of pref value meanings).
This brings us into line with [Safari's latest changes](https://webkit.org/blog/9661/preventing-tracking-prevention-tracking/).
=> Set default cross-origin referer trimming to origin only

mozilla-release/browser/themes/osx/cliqz/theme.css, mozilla-release/browser/themes/windows/cliqz/theme.css
In this fix, we are resorting to default behavior of firefox wrt to border below the URLbar for mac and windows.
this is dealt by `#navigator-toolbox:after` element.
=> DB-2374: fixing border for navigator-toolbox

docker/Dockerfile, mozilla-release/browser/config/cliqz.mozconfig
Fixes #1435
Fixes #1434
The issue seems to be this one: https://bugzilla.mozilla.org/show_bug.cgi?id=1600467,
where the version 6.x of clang, which is also the one shipped with Ubuntu 18.04,
is known to have "miscompilation issues" when applied to the Firefox codebase
(see: https://bugzilla.mozilla.org/show_bug.cgi?id=1594686).
Because it took a while to realize that the issue was from clang, I iterated on
both the Dockerfile and cliqz.mozconfig during the investigation. This commit
changes a bit more than what is strictly needed to fix the issue, and contains
a refreshed Dockerfile. It was both updated and simplified, mostly because the
base image used now ships with more recent versions of various packages that
we need (Ubuntu 19.10).
Last but not least, I propose a few additions to the …
=> Addresses browser crash when built for Linux.

docker/Dockerfile, mozilla-release/browser/config/cliqz.mozconfig
The previous solution of using Ubuntu 19.10 for building was solving the
compilation issue with clang but introduced a backward incompatibility
because of the version of glibc available on the system.
The solution is to use the oldest version of Ubuntu that we want to
support (i.e. 16.04), then install custom tooling on top to allow
building. This is done by installing:
* LLVM/Clang in their version 9 (latest)
* Node.js LTS 12.x
* Aptly from third-party ppa
* Awscli from pypi using pip
* Nasm from source
* Rust toolchain using rustup
This solution gives us a frame to evolve the build of Cliqz for Linux in
the future. We can:
* Bump the base image version to stop supporting an old version of Ubuntu
* Bump versions of individual tools (i.e. Rust, Node.js, Clang, etc.)
=> Restore backward compatibility of Linux builds with 16.04 and 18.04.

mozilla-release/browser/config/cliqz.mozconfig
This PR enables `rust-simd` compile flag which could bring some performance improvement. I already tested building the browser with this option and will now check if the resulting binary runs fine on different Linux distributions.
=> linux: enable rust-simd compile flag

mozilla-release/toolkit/components/extensions/webrequest/WebRequest.jsm
Thanks to FF, now it handles differently the cancel event. They fallback to previous state automatically when request is cancelled.
Before it stops at blank chrome when the request was cancelled.
=> DB-2408: do not close the tab where the link is opened from

cliqz_env.sh, docker/Dockerfile, mozilla-release/toolkit/mozapps/installer/upload-files.mk
Build of Cliqz on Linux started failing a few days ago. It seems to be due to an incompatibility with `libc` that is shipped by default with Ubuntu 16.04 which we used until now to compile and source code from upstream Firefox/build toolchain. The reason we picked such an old version of Ubuntu to compile Cliqz at the time was the following:
* The `libc` version is bound to the linux distribution (and versions shipping from newer distributions usually introduce breaking changes).
* Version of `libc` will determine the compatibility of Cliqz for older systems (Cliqz compiled with `libc` from Ubuntu 18.04 will not be able to run on Ubuntu 16.04).
Hence, we picked the oldest version we could, so that Cliqz can run on as many distributions as possible. It would be possible to have custom …
=> Fix Dockerfile for Linux build

mozilla-release/browser/components/urlbar/UrlbarInput.jsm
We do not have to call this this._resetSearchState method if tab changed.
Because this method gets triggered within this._afterTabSelectAndFocusChange function after a proper check.
=> DB-2430: remove redundant resetSearchState | UrlbarInput.jsm

mozilla-release/browser/config/cliqz.mozconfig, mozilla-release/toolkit/mozapps/extensions/internal/AddonSettings.jsm
`MOZ_ALLOW_LEGACY_EXTENSIONS` - is used no where FF discarded in FF 74
`MOZ_ADDON_SIGNING` is also not used anywhere in project (@alver-cliqz please confirm)
=> DB-2433: allowing experiments on release builds for temporary extension

mozilla-release/browser/app/profile/firefox.js
This reverts commit 246bbde261f2102c205b69c6461ffabf9cd4b061.
As discussed with @konark-cliqz, this setting was causing some breakage that cannot be fixed by just whitelisting in control-center. In order to minimise breakage we will revert the setting, and the extension's anti-tracking features should catch cookies set via dom apis.
=> Revert "Update default cookie policy to reject from unvisited (#1401)"

mozilla-release/browser/app/profile/firefox.js, mozilla-release/modules/libpref/init/all.js
Findings:
corroborator verifies the signature of omni.ja files, this uses addons certificate to verify
=> DB-2439: switch off corroborator and temporary downgrade TLS to 1

mozilla-release/browser/app/profile/firefox.js, mozilla-release/browser/base/content/browser.js, mozilla-release/browser/components/CliqzResources.jsm
We got rid of `matchUrlByString` as we do not have any chance of legacy extension, additionally FF introduced a way to avoid `about:welcome` and use `about:home` instead.
=> DB-2456: remove unecessary functions from Cliqzresource

mozilla-release/browser/base/content/utilityOverlay.js, mozilla-release/browser/components/sessionstore/SessionStore.jsm
Since we now use default FF way to handle home/newtab page, we do not need this fix.
`isBlankPageURL` will take care of cliqz extension URL (`BROWSER_NEW_TAB_URL` === freshtab URL)
=> DB:2459 fixing focus of url bar edge case
